name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get install freeglut3
          sudo apt-get install freeglut3-dev
          sudo apt-get install libsfml-dev
      - name: clean application
        run: make clean
      - name: build application
        run: make 
